# Generated by Django 5.0.4 on 2024-04-14 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
